# Generated by Django 4.2.30 on 2026-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_current_coords_trip_distance_miles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
