# Generated by Django 4.2.30 on 2026-09-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
