# Generated by Django 4.2.30 on 2026-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_add_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='logs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
